# Basket option implementation based on normal model

In [57]:
import numpy as np
from option_models import basket
from option_models import bsm
from option_models import normal

In [58]:
### only run this when you changed the class definition
import imp
imp.reload(basket)

<module 'option_models.basket' from 'C:\\Users\\Noam\\Documents\\GitHub\\PHBS_ASP_2018\\HW3\\option_models\\basket.py'>

In [3]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)

[1 0 0 0]


In [4]:
# Compare the price to normal model formula

norm1 = normal.NormalModel(40)
price_norm = norm1.price(strike=120, spot=100, texp=texp, cp_sign=1)
print(price_basket, price_norm)

26.7639097343 26.5708459579


In [5]:
# A trivial test case 2
# all assets almost perfectly correlated:
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.0001*np.identity(4) + 0.9999*np.ones((4,4))
texp = 5
strike = 120

print( cor_m )

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_norm)

[[ 1.      0.9999  0.9999  0.9999]
 [ 0.9999  1.      0.9999  0.9999]
 [ 0.9999  0.9999  1.      0.9999]
 [ 0.9999  0.9999  0.9999  1.    ]]
26.7613956159 26.5708459579


In [16]:
# A full test set for basket option with exact price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 100
price_exact = 28.0073695

In [17]:
cor_m

array([[ 1. ,  0.5,  0.5,  0.5],
       [ 0.5,  1. ,  0.5,  0.5],
       [ 0.5,  0.5,  1. ,  0.5],
       [ 0.5,  0.5,  0.5,  1. ]])

In [19]:
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_exact)

28.3881270524 28.0073695


# [To Do] Basket option implementation based on BSM model
## Write the similar test for BSM

In [15]:
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=True)

In [10]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
print(price_basket)

[1 0 0 0]
28.751631082489702


In [21]:
# Compare the price to BSM formula

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120
bsm_price = bsm.bsm_price(strike, spot[0], vol[0], texp, intr=0.0, divr=0.0, cp_sign=1)

print(price_basket, bsm_price)

28.751631082489702 28.713486748445934


In [24]:
# A trivial test case 2
# all assets almost perfectly correlated:
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.0001*np.identity(4) + 0.9999*np.ones((4,4))
texp = 5
strike = 120

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
print(price_basket, bsm_price)

28.738539105928172 28.713486748445934


In [28]:
# A full test set for basket option with exact price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 100

price_exact = 28.0073695
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)

print(price_basket, price_exact)

27.42010965333697 28.0073695


# Spread option implementation based on normal model

In [3]:
# A full test set for spread option

spot = np.array([100, 96])
vol = np.array([0.2, 0.1])
weights = np.array([1, -1])
divr = np.array([1, 1])*0.05
intr = 0.1
cor_m = np.array([[1, 0.5], [0.5, 1]])
texp = 1
strike = 0
price_exact = 8.5132252

In [4]:
# MC price based on normal model
# make sure that the prices are similar

np.random.seed(123456)
price_spread = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)
print(price_spread, price_exact)

8.34885280723 8.5132252


# Spread option implementation based on BSM model

In [6]:
# Once the implementation is finished the BSM model price should also work
price_spread = basket.basket_price_mc(
    strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=True)

In [7]:
# You also test Kirk's approximation
price_kirk = basket.spread_price_kirk(strike, spot, vol, texp, 0.5, intr, divr)
print(price_kirk)

8.51322522955


# [To Do] Complete the implementation of basket_price_norm_analytic
# Compare the MC stdev of BSM basket prices from with and without CV

In [8]:
# The basket option example from above

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 100

In [35]:
### Make sure that the analytic normal price is correctly implemented
Normal_Analytic = basket.basket_price_norm_analytic(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, cp_sign=1)
print(Normal_Analytic)

28.209479177387816


In [45]:
#Price of BSM with CV

price_basket_cv = basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m, intr=0, divr=0, cp_sign=1, n_samples=10000)
print(price_basket_cv)

[28.277454723250504, 0.4133815146929152]


In [44]:
#Price of BSM without CV

price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
print(price_basket)

27.42010965333697


In [31]:
# Run below about 100 times and get the mean and stdev

### Returns 2 prices, without CV and with CV 
# price_basket = basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m)

In [81]:
price = np.zeros(100)

for k in range(100):
    #price[k] = basket_price_100(strike, spot, vol, weights, texp, cor_m)
    price[k]= basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m, 
    intr=0.0, divr=0.0, cp_sign=1, n_samples=10000)
    #price_100 = np.mean(price)
    #std = np.std(price)
print(price)

#didnt know how to fix this error, but was trying to reach a point where the mean and Std with the CV is lower than that without CV. 

ValueError: setting an array element with a sequence.

In [66]:
Basket_CV = basket_price_100(strike, spot, vol, weights, texp, cor_m, intr=0, divr=0, cp_sign=1, n_samples = 10000, m_repeat=100)
print(Basket_CV)

[[27.566752423198636, -0.3198693306582996], [28.277454723250504, 0.4133815146929152], [27.663184979854396, -0.2860155064411245], [28.386459838097288, 1.099961050438882], [28.519177352318085, 0.6465877440477463], [28.555726580815147, 0.9884976616789167], [28.08557385436927, -0.5040761472418005], [26.999953338757145, -1.6626660512969806], [28.550312461653782, 0.8911280771656749], [28.312539298260614, 0.6221984448045106], [27.810811700189294, -0.35012821520894377], [27.05530549127701, -1.3089774744044256], [27.64108778475085, 0.2942764072579891], [27.84883619711572, -0.6363257536663447], [29.755756256507144, 1.7619569458151254], [28.737788668065104, 1.1117696251963238], [28.35347981872284, 0.44073699035187985], [27.52182730123382, -0.41997025397722965], [27.517046932007222, -1.4460356036072426], [27.715539967588825, -0.053388787689865325], [28.27165705526017, 0.13915052152473706], [28.646723792688462, 0.36892345667382287], [27.23953892390427, -1.4225889500473698], [27.53906219519273, -0.4